version: '3.9'

services:
  api:
    build: .
    ports:
      - '8080:8080'
  db:
    image: 'postgres'
    restart: always
    ports:
    - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 'asd123'
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: