version: '3.9'

services:
  api:
    build: .
    depends_on:
      - db
    ports:
      - '5000:5000'
    command:
      - nodemon
      - app.js
    restart: always
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: development
      POSTGRES_PASSWORD: 'asd123'
  db:
    image: 'postgres'
    restart: always
    ports:
    - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 'asd123'
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: